export const GET_CLIPS = 'GET_CLIPS'
export const GET_CLIPS_SUCCESS = 'GET_CLIPS_SUCCESS'
export const GET_CLIPS_FAILED = 'GET_CLIPS_FAILED'

export const DELETE_BUBBLE = 'DELETE_BUBBLE'
export const DELETE_BUBBLE_SUCCESS = 'DELETE_BUBBLE_SUCCESS'
export const DELETE_BUBBLE_FAILED = 'DELETE_BUBBLE_FAILED'

export const REORDER_CLIPS = 'REORDER_CLIPS'

export const UPDATE_SELECTED_INDEX = 'UPDATE_SELECTED_INDEX'
